import * as Console from "effect/Console"
import * as Effect from "effect/Effect"
import * as Layer from "effect/Layer"
import { resolveSource, makeSourceContext } from "alchemy/Cloudflare/Workers"
import { ArtifactStore, createArtifactStore, scopedArtifacts } from "alchemy/Artifacts"
import { PlatformServices, runMain } from "alchemy/Util/PlatformServices"

// Run the deployed Worker's bundler against its real entry and dependencies.
// Resource-specific DO export bindings are generated by Alchemy during deploy;
// this credential-free check does not produce a deployable release artifact.
const check = Effect.gen(function* () {
  const props = { main: new URL("../apps/cluster/src/Worker.ts", import.meta.url).pathname }
  const source = yield* resolveSource(props)
  const result = yield* source.build(
    makeSourceContext({
      id: "ClusterWorker",
      workerName: "janitor-cluster-check",
      props,
      compatibility: { date: "2026-09-05", flags: ["nodejs_compat"] },
      stack: { name: "Janitor", stage: "production" },
    }),
  )
  if (!result.bundle) return yield* Effect.die(new Error("Worker bundle was not generated"))
  yield* Console.log(
    `Worker bundle checked: ${result.bundle.files.length} files, hash ${result.bundle.hash}`,
  )
}).pipe(
  Effect.provide(
    scopedArtifacts("ClusterWorker").pipe(
      Layer.provide(Layer.succeed(ArtifactStore, createArtifactStore())),
    ),
  ),
  Effect.provide(PlatformServices),
  Effect.scoped,
)

runMain(check)
