import { createHash, randomUUID } from "node:crypto"
import { spawnSync } from "node:child_process"
import { mkdtemp, readFile, writeFile, rm, mkdir } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"

const digest = (bytes) => createHash("sha256").update(bytes).digest("hex")
function tar(args) {
  const result = spawnSync("tar", args, { encoding: "utf8" })
  if (result.status !== 0) throw new Error(`archive command failed: ${result.stderr}`)
}

// Prototype bucket exposes put(key, bytes), get(key) -> bytes, delete(key).
// R2 streaming, durable pointer CAS and fencing are not simulated by this API.
export async function saveCheckpoint({ dir, bucket, commit, failBeforeCommit = false }) {
  const temporary = await mkdtemp(join(tmpdir(), "janitor-checkpoint-"))
  const id = randomUUID()
  try {
    const archivePath = join(temporary, "workspace.tar")
    tar(["--exclude=./cache", "-cf", archivePath, "-C", dir, "."])
    const bytes = await readFile(archivePath)
    const archiveKey = `checkpoints/${id}/workspace.tar`
    const manifestKey = `checkpoints/${id}/manifest.json`
    const manifest = {
      version: 1,
      id,
      archiveKey,
      sha256: digest(bytes),
      size: bytes.length,
      format: "tar",
      exclusions: ["cache"],
    }
    await bucket.put(archiveKey, bytes)
    await bucket.put(manifestKey, Buffer.from(JSON.stringify(manifest)))
    if (failBeforeCommit) throw new Error("injected loss before checkpoint pointer commit")
    await commit({ manifestKey, sha256: digest(Buffer.from(JSON.stringify(manifest))) })
    return manifest
  } finally {
    await rm(temporary, { recursive: true, force: true })
  }
}

export async function restoreCheckpoint({ target, bucket, pointer }) {
  const manifestBytes = await bucket.get(pointer.manifestKey)
  if (digest(manifestBytes) !== pointer.sha256) throw new Error("manifest checksum mismatch")
  const manifest = JSON.parse(manifestBytes)
  if (manifest.version !== 1 || manifest.format !== "tar")
    throw new Error("unsupported checkpoint format")
  const bytes = await bucket.get(manifest.archiveKey)
  if (bytes.length !== manifest.size || digest(bytes) !== manifest.sha256)
    throw new Error("archive checksum mismatch")
  // Only handles archives generated by this fixture. A production extractor
  // must reject path traversal and unsafe link targets inside repository data.
  await mkdir(target, { recursive: false })
  const temporary = await mkdtemp(join(tmpdir(), "janitor-restore-"))
  try {
    const archivePath = join(temporary, "workspace.tar")
    await writeFile(archivePath, bytes)
    tar(["-xf", archivePath, "-C", target])
  } finally {
    await rm(temporary, { recursive: true, force: true })
  }
  return manifest
}
